### ISSUE TITLE
Get event version from the eventstore

### ISSUE THREAD

**Issue by Akii** [dbellettini/broadway-eventstore#3]
It's (imho) very wrong to generate the events version (https://github.com/dbellettini/broadway-eventstore/blob/master/src/EventStore/Broadway/BroadwayEventStore.php#L67).

The version is a very important piece when it comes to validate applying them to aggregates as well as resolving conflicts. Instead, the information should come directly from the store. This can be achieved via the URL "aggregate-identifier/version" or, when the EmbedMode::RICH is used, it will be part of the payload.

This is probably also a "downstream" bug/feature that must then be implemented in the eventstore-client. Just checked that I patched the file StreamFeed/Entry to return the event version, so the eventstore-client has no API for this yet (it really should).

If you guys agree, I'd create a PR for both the client and this package getting the event version either from the payload or url.

**Comment by afoeder** [comment]
:+1: Sounds sane by reading.

**Comment by dbellettini** [comment]
This is worse than I assumed, using `$i++` had been hiding #1

**Comment by dbellettini** [comment]
@Akii I'd appreciate your PR on the main project

**Comment by Akii** [comment]
Well you fixed it in the wrong package :D. IMO the `entry` should have a getter for the version, and here we use it. Additionally, if sorting by version, it should be done in the end (again IMO). I personally would rely on the eventstore for sorting here though.

**Comment by dbellettini** [comment]
Ok, I added `getVersion()` to `Entry` in the main package, sorting is still pending since I would like to do something that detects if we are going forward or backward and sort events consistently
