### ISSUE TITLE
[BUG] Check that we have events to write

### ISSUE THREAD

**Issue by pmartelletti** [dbellettini/broadway-eventstore#5]
In EventStore implementation, the append method always try to write to stream, even if there are no events to write. This causes a 400 error to be thrown, because is trying to write empty content in the stream.

I suggest doing a check in the append method:

``` php
if(count($events) > 0) {
            try {
                $this
                    ->eventStore
                    ->writeToStream(
                        $id,
                        new WritableEventCollection($events),
                        $playhead - 1
                    )
                ;
            } catch (WrongExpectedVersionException $e) {
                dd($e->getMessage());
                throw new BroadwayOptimisticLockException($e->getMessage());
            }
        }

```

@dbellettini what do you think?

**Comment by dbellettini** [comment]
I'll have a look to DBAL implementation and try to replicate the same behaviour

**Comment by dbellettini** [comment]
ok, I think that giving an empty array to append does not make sense, but I want to make the EventStore implementation as interchangeable as possible. I will do that this weekend

**Comment by pmartelletti** [comment]
:+1:
